name: pipeline-ci/cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PUSH }}
          aws-region: us-east-1
      
      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build image, tag e push
        run: |
          docker build -t site-praticas-devops:v1.0 .
          docker tag site-praticas-devops:v1.0 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/site_prod:v1.0
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/site_prod:v1.0
  job2:
    name: deploy 
    needs: job1
    runs-on: ubuntu-latest
    steps: 
    - name: Deploy ssh
      run: |
        echo "${{ secrets.CHAVE_SITE_PROD }}" > chave_site.pem << EOF
        chmod 400 chave_site.pem  
        ssh -i chave_site.pem -o StrictHostKeyChecking=no ec2-user@${{secrets.PUBLIC_IP}} 
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/site_prod:v1.0
          docker run -d -p 80:80 --name site-prod ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/site_prod:v1.0
          docker ps
          rm chave_site.pem 
        EOF
        
